Off-by-one typo
JordanMartinez/purescript-jordans-reference pull request #433
Opened 2020-02-14 04:55 UTC by milesfrain

This would read a lot easier if arrays indices were 1-based

2020-02-14 12:56 UTC, JordanMartinez commented on 21-Hello-World/06-Type-Level-Programming/ReadMe.md
> +Here's an example in code. If the array is empty or only has fewer than `n - 1` elements, the function can only throw an error when we try to reference a non-existent element at index `n`. If the arr
This should probably be rendered as "...or has fewer than..." rather than the current "...or only has fewer than..."

2020-02-14 12:58 UTC, JordanMartinez commented on 21-Hello-World/06-Type-Level-Programming/ReadMe.md
> +elemAtIndex 3 (IndexedArray 3 ["a", "b"]) -- compiler error!
Perhaps to make this more obvious, the elements of the array should be changed from String to Int?
```purescript
elemAtIndex 3 (IndexedArray 3 [0, 1, 2, 3] -- 3
elemAtIndex 3 (IndexedArray 1 [0, 1] -- compiler error!
```

2020-02-14 12:59 UTC, JordanMartinez requested changes
I agree that it does read better that way.

Could you account for the comments I made?

2020-03-13 14:50 UTC, JordanMartinez commented
@milesfrain Perhaps you've forgotten about this PR, but could you make the changes I mentioned above?

2020-03-13 16:29 UTC, milesfrain commented
Thanks for the reminder. I'll get back to this on Wednesday.

On Fri, Mar 13, 2020, 8:50 AM JordanMartinez <notifications@github.com>
wrote:

> @milesfrain <https://github.com/milesfrain> Perhaps you've forgotten
> about this PR, but could you make the changes I mentioned above?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JordanMartinez/purescript-jordans-reference/pull/433#issuecomment-598757397>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3JWOJ4XYDO4R4HT5TUD5LRHJB23ANCNFSM4KVAWLPA>
> .
>

2020-03-13 20:00 UTC, milesfrain commented
@JordanMartinez Should be good to merge now.

2020-03-13 20:18 UTC, JordanMartinez commented
Thanks! I'll merge this when I get off work.

2020-03-14 00:59 UTC, JordanMartinez approved these changes

2020-03-14 00:59 UTC, merged

2020-03-14 00:59 UTC, JordanMartinez commented
Thanks!